color: null
description: null
fieldLayouts:
  aaf1a611-7cf6-4cf9-9a09-9bccbded7389:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-12-05T15:44:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b49662b8-92dd-4ab8-99d8-d30dfc2eb738
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-12-05T15:45:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3ec10970-9304-4c14-8c1b-18726aa141b9 # Intro Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6935074-a2a4-4773-81a2-d3def470443e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7433b05f-ef6e-469f-91c4-d73e5a324af6
        userCondition: null
handle: impressum
hasTitleField: true
icon: null
name: Impressum
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
