color: null
description: null
fieldLayouts:
  1350ec69-cdd9-42f9-87e6-ad2a84be2a08:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-24T20:04:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 02daa00e-fbb7-4eb8-a8f5-94f550eeb331
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-25T08:15:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 331539bf-f337-402c-b9cc-24ad01f1d9de # Short Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dfd5a565-edff-45cf-8655-d0b416290d90
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-25T08:15:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ee2824c3-8d7f-418a-b418-244c0e84e62f # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1d953cb0-be9b-415c-8b0b-a6ba2db6d2f7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-25T08:15:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d41bdc89-fe25-44f0-8d25-055ea6bbf491 # Hero Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e42d71fa-f3b2-4087-847d-98bdfc98a5fc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-25T08:15:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bbac927c-8f02-4c01-b787-5b93491ae2ed
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6383bf0e-52e3-4d16-a63e-53a267d8478e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-28T17:55:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0cde3055-d952-46c0-8db8-6cb374162773 # Content Sections
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65fbcb77-bc58-45e3-9395-ed975fba98b9
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68ee9007-f318-4f5b-9ca4-67d960f90131
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-25T08:15:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5a2e10e5-d101-4b1e-8f49-e396385ff908 # Project URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72e3fed9-4425-4457-a511-066352d3d910
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-25T08:15:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 05d7ebc9-41b0-46e0-a54f-179adea38497 # GitHub URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c981cd6-a8c3-4400-a32a-6dfde113e734
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-25T08:15:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 54ec80f0-65f7-4d05-a156-a18331c71227 # Publish Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6703dee0-3e7f-4d53-a5c5-27c9956c7587
            userCondition: null
            warning: null
            width: 100
        name: Meta
        uid: f64110ff-cb38-4741-b0cd-6d0f2ae38574
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-29T08:10:54+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ab648d29-9a8e-42ce-8ce1-ea2b834f869a # Tech Stack Items
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 547aab8f-3f4d-4c85-b34f-45e75376ee94
            userCondition: null
            warning: null
            width: 100
        name: Tech
        uid: a7e7fdf5-4ec9-4a31-9175-7e9eaedd4217
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-11-29T10:55:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cdba1535-dc8b-460e-b34a-2c489560a09d # Gallery
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fce51bce-fff7-49cb-8991-58036d25eb45
            userCondition: null
            warning: null
            width: 100
        name: Gallery
        uid: 2e92d73e-7927-4668-9d59-342a750949f7
        userCondition: null
handle: project
hasTitleField: true
icon: null
name: Project
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
