altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  6677a924-77f8-4329-b677-c92316214cad:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-25T08:22:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 885eae88-6dfc-4e8d-9e53-34dda73f1e24
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cf9214b8-6455-40eb-91fb-676f6855fd3c
        userCondition: null
fs: imagesFilesystem
handle: images
name: Images
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
