columnSuffix: null
handle: isCollapsible
instructions: null
name: 'Is Collapsible'
searchable: false
settings:
  default: false
  offLabel: 'Not collapsible'
  onLabel: Collapsible
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
