columnSuffix: null
handle: shortDescription
instructions: null
name: 'Short Description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: 'A brief one-line summary'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
