defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3d64e561-8a19-44d2-93bc-c83b592eeb06 # Contact
handle: contact
maxAuthors: 1
name: Contact
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  522e8e10-5cd3-4e4f-905e-6fbb9b08136c: # Nico's portfolio
    enabledByDefault: true
    hasUrls: true
    template: contact/_entry.twig
    uriFormat: contact
type: single
