defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e326f135-ef60-4568-9162-6224f7492eaf # Contacts
handle: contacts
maxAuthors: 1
name: Contacts
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  522e8e10-5cd3-4e4f-905e-6fbb9b08136c: # Nico's portfolio
    enabledByDefault: true
    hasUrls: true
    template: contacts/_entry.twig
    uriFormat: contacts
type: single
