defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b7ba979d-16bd-4395-9aad-196ce5bb038d # Hompage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  522e8e10-5cd3-4e4f-905e-6fbb9b08136c: # Nico's portfolio
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
