defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 0d1c4f38-976d-4e09-a24c-f887adea8c02 # Project
handle: projects
maxAuthors: 1
name: Projects
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  522e8e10-5cd3-4e4f-905e-6fbb9b08136c: # Nico's portfolio
    enabledByDefault: true
    hasUrls: true
    template: projects/_entry.twig
    uriFormat: 'projects/{slug}'
type: channel
